CREATE DATABASE IF NOT EXISTS BIONIC;
USE BIONIC;

CREATE TABLE IF NOT EXISTS RETAIL (
	RETAIL_ID INT NOT NULL AUTO_INCREMENT, 
	EMPLOYEE_NAМE VARCHAR(40) NOT NULL,
	EMPLOYEE_SURNAМE VARCHAR(40) NOT NULL,
	DATE_OF_BIRTH DATE, 
	DATE_OF_EMPLOYMENT DATE,
	PRIMARY KEY (RETAIL_ID)
);

CREATE TABLE IF NOT EXISTS CUSTOMER (
	CUSTOMER_ID INT NOT NULL AUTO_INCREMENT,
	CUSTOMER_NAМE VARCHAR(40) NOT NULL,
	CUSTOMER_SURNAME VARCHAR(40) NOT NULL,
	DATE_OF_BIRTH DATE, 
	CITY VARCHAR(60),
	STREET_NAME VARCHAR(60),
	HOUSE_NUMBER INT,
	AREA_CODE VARCHAR(10),
	EMAIL_ADDRESS VARCHAR(60) NOT NULL UNIQUE,
	CELLPHONE_NUMBER VARCHAR(20) NOT NULL UNIQUE,
	PRIMARY KEY (CUSTOMER_ID)
);
	
CREATE TABLE IF NOT EXISTS RETAIL_CUSTOMER (
	RETAIL_ID INT NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	FOREIGN KEY (RETAIL_ID) REFERENCES RETAIL(RETAIL_ID),
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT (
	PRODUCT_ID INT NOT NULL AUTO_INCREMENT,
	PRODUCT_NAМE VARCHAR(100) NOT NULL UNIQUE,
	PRODUCT_PRICE DOUBLE NOT NULL,
	PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS ORDER_RULE (
	ORDER_RULE_ID INT NOT NULL AUTO_INCREMENT,
	PRODUCT_ID INT NOT NULL,
	AMOUNT INT NOT NULL,
	TOTAL INT NOT NULL,
	PRIMARY KEY (ORDER_RULE_ID),
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);
	
CREATE TABLE IF NOT EXISTS ORDERS (
	ORDER_ID INT NOT NULL AUTO_INCREMENT,
	CUSTOMER_ID INT NOT NULL,
	ORDER_RULE_ID INT NOT NULL,
	ORDER_DATE DATE,
	PRIMARY KEY (ORDER_ID),
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
	FOREIGN KEY (ORDER_RULE_ID) REFERENCES ORDER_RULE(ORDER_RULE_ID)
);